In [1]:
import pandas as pd
import os
import librosa
import librosa.display

In [2]:
import struct

class WavFileHelper():
    
    def read_file_properties(self, filename):

        wave_file = open(filename,"rb")
        
        riff = wave_file.read(12)
        fmt = wave_file.read(36)
        
        num_channels_string = fmt[10:12]
        num_channels = struct.unpack('<H', num_channels_string)[0]

        sample_rate_string = fmt[12:16]
        sample_rate = struct.unpack("<I",sample_rate_string)[0]
        
        bit_depth_string = fmt[22:24]
        bit_depth = struct.unpack("<H",bit_depth_string)[0]

        return (num_channels, sample_rate, bit_depth)

In [3]:
wavfilehelper = WavFileHelper()

In [4]:
fulldatasetpath = 'E:\\2021\\UrbanSound8K\\audio'

metadata = pd.read_csv('E:\\2021\\UrbanSound8K\\metadata\\UrbanSound8K.csv')

In [5]:
audiodata = []
for index, row in metadata.iterrows():
    
    file_name = os.path.join(os.path.abspath('E:\\2021\\UrbanSound8K\\audio'),'fold'+str(row["fold"])+'/',str(row["slice_file_name"]))
    data = wavfilehelper.read_file_properties(file_name)
    audiodata.append(data)

#Convert into a Panda dataframe
audiodf = pd.DataFrame(audiodata, columns=['num_channels','sample_rate','bit_depth'])

In [6]:
print(audiodf.num_channels.value_counts(normalize=True))

2    0.915369
1    0.084631
Name: num_channels, dtype: float64

In [12]:
audiodf

      num_channels  sample_rate  bit_depth
0                2        44100         16
1                2        44100         16
2                2        44100         16
3                2        44100         16
4                2        44100         16
5                2        44100         16
6                2        44100         16
7                2        44100         16
8                2        44100         16
9                2        44100         16
10               2        44100         16
11               2        44100         16
12               2        44100         16
13               2        44100         16
14               2        44100         16
15               2        44100         16
16               2        44100         16
17               2        44100         16
18               2        44100         16
19               2        44100         16
20               2        44100         16
21               2        44100         16
22               2        44100         16
23               2        44100         16
24               2        44100         16
25               2        44100         16
26               2        44100         16
27               2        44100         16
28               2        44100         16
29               2        44100         16
...            ...          ...        ...
8702             1        44100         16
8703             1        44100         16
8704             1        44100         16
8705             1        44100         16
8706             1        44100         16
8707             1        44100         16
8708             1        44100         16
8709             2        44100         16
8710             2        44100         16
8711             2        44100         16
8712             2        44100         16
8713             2        44100         16
8714             2        44100         16
8715             2        44100         16
8716             2        44100         16
8717             2        44100         16
8718             2        44100         16
8719             2        44100         16
8720             2        44100         16
8721             2        44100         16
8722             2        44100         16
8723             2        44100         16
8724             2        44100         16
8725             2        44100         16
8726             2        44100         16
8727             2        44100         16
8728             2        44100         16
8729             2        44100         16
8730             2        44100         16
8731             2        44100         16

[8732 rows x 3 columns]